# Generated by Django 4.0.6 on 2022-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birth_day_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_profile_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
